### PR TITLE
Update safesearch-not-supported

### PR DESCRIPTION
**Pull request by sfsef**
Mail.ru group is making different services, including searching service. 
Search domains: mail.ru and poisk.mail.ru

### CODE REVIEW

**Comment by sfsef** [comment]
Added rambler (26 millions people visit this site every month) and nigma

**Comment by romaincointepas** [comment]
We can't block `mail.ru`, that would be too wide a net. If you can find a specific search-only hostname we could block that would work.

Would blocking `nova.rambler.ru` instead of `rambler.ru` be better? That's the domain I'm getting after searching.

Ok for `nigma.eu`.

Ideally, could you reach out to them first to see if they support enforcing SafeSearch at the DNS level?

**Comment by sfsef** [comment]
Well, give me a second. I'll push commit

**Comment by sfsef** [comment]
go.mail.ru - that's the domain I got after searching

I agree with you. 
_nova.rambler.ru_ would be better

**Pull request closed without merging**
