### PR TITLE
Add Blocklist: HaGeZi - Multi PRO

### PR DESCRIPTION
**Pull request by hagezi**
Please add my Blocklist Multi PRO - Extended protection: https://github.com/hagezi/dns-blocklists#pro

My blocklists are based on [various sources](https://github.com/hagezi/dns-blocklists/blob/main/usedsources.md) and my own blacklists. They were designed to avoid [false positive domains](https://github.com/hagezi/dns-blocklists/blob/main/whitelist.txt) as much as possible and not to block any needed features. [Dead hosts](https://github.com/hagezi/dns-blocklists/blob/main/deadlist.txt) are regularly removed from the lists to keep them as small as possible. They are updated and maintained daily.

For more information see the [README](https://github.com/hagezi/dns-blocklists/blob/main/README.md).

Thanks,
Gerd

### CODE REVIEW

**Comment by merj1928** [comment]
can only say: finally take up these lists.

**Comment by hagezi** [comment]
https://github.com/nextdns/blocklists/pull/65

**Comment by merj1928** [comment]
> https://github.com/nextdns/blocklists/pull/65

??

**Comment by hagezi** [comment]
@merj1928 
The repository for the NextDNS blocklists has changed, so I should create a new pull request in it.

**Comment by merj1928** [comment]
Hoffen wir dann mal, das es mit deinen Listen klappt 👍

**Pull request closed without merging**
