### PR TITLE
Delete brave search,ecosia,and startpage from safesearch-not-supported

### PR DESCRIPTION
**Pull request by arfshl**
brave search and ecosia have a safesearch and startpage have a family filter

### CODE REVIEW

**Comment by Oakwas** [comment]
All the search engines you listed have safe search, but they are not enforced (they do not meet CIPA compliance).

AFAIK brave is testing this feature.
https://community.brave.com/t/feature-request-enforcing-or-locking-safe-search-or-strict-search-in-brave-search/307897
https://community.brave.com/t/brave-safe-search-set-to-strict-and-p-rn-websites-still-come-in-the-results/262075/12

Not sure about Startpage and Ecosia.
https://community.cleanbrowsing.org/topic/startpage-com-a-search-engine-is-not-forced-on-safe-mode-adult-filter/

**Comment by Oakwas** [comment]
Ecosia have support for [enforced safe search](https://ecosia.helpscoutdocs.com/article/174-does-ecosia-have-safe-search). I'm not sure if NextDNS support this. 
@romaincointepas

**Comment by remusao** [comment]
Hi @Oakwas,

I am a developer at Brave. I wanted to confirm that we have implemented http://safesearch.brave.com/ to enforce safe-search on Brave Search. This is mentioned in the last answer of the threads you linked above. Is there anything else required to be removed from the blocklist?

Best,
Rémi

**Comment by romaincointepas** [comment]
@remusao for us to be able to enforce safesearch, we need to be able to enforce it at the DNS level by rewriting the answer for one or more domains.

Here is how it works for Google:
https://support.google.com/websearch/answer/186669 (section *Lock SafeSearch for a school, workplace, or home network you manage*)

With our SafeSearch parental control setting, we either enforce it at the DNS level (when supported), or block the search engine from being used.

**Comment by remusao** [comment]
Thanks @romaincointepas. I might be missing something, but from what I understand you should then be able to map `search.brave.com` to `safesearch.brave.com` to enforce safe search at the DNS level for Brave Search. Or is there any other requirement here that is not satisfied?

**Comment by romaincointepas** [comment]
@remusao are you enforcing it based on different IPs being reached or based on the Host?

**Comment by remusao** [comment]
> @remusao are you enforcing it based on different IPs being reached or based on the Host?

These are two different Cloudfront distributions so hitting and resolving `safesearch.brave.com` should always lead you to a version of Brave Search where "safe search" is being enforced.

**Comment by romaincointepas** [comment]
@remusao that type of setup will not work for DNS-based enforcing. The way everyone is doing this is to enforce safesearch when search.brave.com hits a specific different IP or set of IPs, so that would be hard to set up if those domains are behind a CDN (same IPs, different hosts).

Another way to do it would be to enforce safesearch when a specific hostname does not resolve (usually called a canary domain), or to use a specific domains for adult results (that we would also block).

**Comment by arfshl** [comment]
18.155.68.28 search.brave.com
18.155.68.103 search.brave.com
18.155.68.23 search.brave.com
18.155.68.94 search.brave.com

Hosts for enforcing safesearch for brave search,get IP from [Digitalocean DNS Lookup](https://www.digitalocean.com/community/tools/dns?domain=safesearch.brave.com)

**Comment by Oakwas** [comment]
Isn't this how DuckDuckGo enforce safe search?
https://help.duckduckgo.com/duckduckgo-help-pages/features/safe-search/'

**Comment by remusao** [comment]
@romaincointepas Thanks for the answer, to add up to what @arfshl and @Oakwas wrote above, I wanted to clarify that `safesearch.brave.com` and `search.brave.com` will resolve to different sets of IPs so unless I am missing something, then this approach should work (i.e. mapping search.brave.com -> safesearch.brave.com at the DNS level).

**Comment by arfshl** [comment]
I guess it can be done with the rewrite feature

**Comment by romaincointepas** [comment]
@remusao I tried CNAME'ing, it doesn't seem to work.

You can easily try it as well with NextDNS by adding `search.brave.com` -> `safesearch.brave.com` as a Rewrite (under the Settings tab).

**Comment by romaincointepas** [comment]
Closing as we are splitting up this monorepo. Feel free to open an issue/PR on https://github.com/nextdns/no-safesearch when you have a working solution (looking forward!).

**Pull request closed without merging**
