### PR TITLE
Add hackernews service

### PR DESCRIPTION
**Pull request by thetimetraveler**

### CODE REVIEW

**Comment by romaincointepas** [comment]
I'm not really seeing the use case for blocking this on a network, is that for *self-control*?

**Comment by thetimetraveler** [comment]
Yes, I agree but currently there aren't any other available mechanisms. I also posted https://github.com/nextdns/metadata/issues/549

**Comment by romaincointepas** [comment]
Got it. I'm going to have to close this as this will never make it in Parental Control. Feature request duly noted to be able to apply recreation time to denylist items.

**Comment by thetimetraveler** [comment]
I understand. But I see Reddit is currently included as a service?

**Comment by romaincointepas** [comment]
Reddit has tons of NSFW stuff on it, and a very large audience. I highly doubt some parents would like to block hackernews for their kids :)

**Pull request closed without merging**
