### PR TITLE
Create hotstar in parental control

### PR DESCRIPTION
**Pull request by anshul78**

### CODE REVIEW

**Comment by romaincointepas** [comment]
Is this Disney+? I'm wondering if we should just add those domains under Disney+.

**Comment by anshul78** [comment]
Hotstar has tied with Disney+. However, it also has its own content and so can be considered a standalone service in itself.

**Comment by romaincointepas** [comment]
Do you have Disney+ (https://www.disneyplus.com) in India? Or is it under Hotstar?

**Comment by anshul78** [comment]
Opening the link is opening Hotstar. So it seems Disney+ is under Hotstar.

**Comment by Nisten-netizen** [comment]
-Hotstar is a standalone service outside of India (for example in US the url would be https://www.hotstar.com/us)
-Disney+Hotstar is a combined service exclusive to India (https://www.hotstar.com/in)

**Comment by romaincointepas** [comment]
We may add this soon.

**Pull request closed without merging**
