### PR TITLE
Added company related domains

### PR DESCRIPTION
**Pull request by evrifaessa**
This PR adds more than 40 domains for different companies.

### CODE REVIEW

**Comment by evrifaessa** [comment]
Anyone to merge this?

**Comment by quantumpacket** [comment]
Why close the PR?

**Comment by evrifaessa** [comment]
> Why close the PR?

It's been 5 months and I don't want to keep forked repositories in my account. I also asked for somebody to check and possibly merge this in January but nobody seemed to care. Have a nice day.

**Comment by crssi** [comment]
@romaincointepas and @rs would you mind doing something with this and other opened issues?

**Pull request closed without merging**
