### PR TITLE
Create fakerando-domains.json

### PR DESCRIPTION
**Pull request by xopez**
More details on github repo: https://github.com/SoftCreatR/fakerando-domains

### CODE REVIEW

**Review by SoftCreatR — APPROVED** [review]

**Comment by romaincointepas** [comment]
Could you share some examples of a restaurant website vs. one that mimics it?

**Comment by SoftCreatR** [comment]
> Could you share some examples of a restaurant website vs. one that mimics it?

Restaurant page: https://etnagladbeck.de
Fake page: https://www.pizzeria-etna-gladbeck.de (which also ranks higher on Google)

**Comment by xopez** [comment]
Another example:
Restaurant Page: https://schnellekartoffel.de/ with own online shop: https://shop.schnellekartoffel.de/
abd fake: https://www.dieschnellekartoffelerfurt.de/

**Comment by romaincointepas** [comment]
Holy shit, this is nasty.

Not sure where this would fit on NextDNS though, we like to keep blocklists privacy-related.

**Comment by xopez** [comment]
On the other side it would be nice to see it in NextDNS since not all devices are able to do adblock like mobile browsers. So DNS based blocking itself would fit in my opinion.

**Comment by crssi** [comment]
FYI: Tried the two examples and it seems to be covered by OISD.

Cheers

**Comment by quantumpacket** [comment]
> Not sure where this would fit on NextDNS though, we like to keep blocklists privacy-related.

Are these websites acting as a middle-man to take a cut from the customer's transaction and then fulfilling the order through the real site? Or are they outright stealing the customer's money and data? If the latter, then maybe this could be put under the threat feeds as it's similar to a phishing site.

**Comment by xopez** [comment]
> 
> 
> FYI: Tried the two examples and it seems to be covered by OISD.
> 
> Cheers

Yes, I have seen this for a few random picked domains. oisd is only a combination of multiple hostlists. Would be nice to know where it's included.

**Comment by romaincointepas** [comment]
I don't feel like adding an archived repo, and this doesn't feel like a Privacy or Security type of things either.

**Pull request closed without merging**
