### PR TITLE
Replace CHEF-KOCH Spotify list [EOL] with SpotAdBlock

### PR DESCRIPTION
**Pull request by nitrohorse**
Looks like [CHEF-KOCH's list](https://github.com/CHEF-KOCH/Spotify-Ad-free/issues/12#issuecomment-586720054) is not maintained anymore so I suggest removal or replacement with [x0uid's list](https://github.com/x0uid/SpotifyAdBlock).

### CODE REVIEW

**Comment by romaincointepas** [comment]
CHEF-KOCH mentions that it's not possible anymore to block ads on spotify by simply blocking domain. If he's correct, why should x0uid's list work?

**Comment by ZeroDot1** [comment]
Domain blocking for spotify does not work, I have checked it out.
I recommend to remove this list.

**Comment by nitrohorse** [comment]
@romaincointepas you raise a good question. CHEF-KOCH states hosts blocking is an "inefficient" way of blocking and has stopped supporting their list -- but it is still possible. I think Spotify pushes changes frequently enough to where list maintainers need to continually watch for and push changes. So maybe having a Spotify blocklist is a bit futile, _however_ x0uid appears to be actively maintaining their list which helps the situation for end users still relying on hosts blocking.

**Comment by anshul78** [comment]
I tried CHEF-KOCH's list and it broke Spotify. I cannot say whether any ads were blocked as the app stopped streaming after 10 seconds for any song. 

This may happen with this list too. So I think there shouldn't be any Spotify blocklist, as it can create more problems than it can solve.

**Comment by nitrohorse** [comment]
Looks like https://github.com/CHEF-KOCH/Spotify-Ad-free now returns a 404.

**Pull request closed without merging**
