### PR TITLE
Added 3 variants of Steven Black Hosts

### PR DESCRIPTION
**Pull request by gitpubber**
Currently, Steven Black Hosts is present but only one variant is provided, ie, the first one which contains only Unified hosts.

This adds 3 other variants,

Unified hosts + fakenews + gambling + porn + social

,

Unified hosts + fakenews + gambling + social

and

Unified hosts + fakenews + gambling .

Thank you in advance

CC @rs

### CODE REVIEW

**Comment by gitpubber** [comment]
@romaincointepas

**Comment by beerisgood** [comment]
Doesn't make sense as this would end in censored internet.

**Comment by gitpubber** [comment]
What do you mean by censored? i am not telling to make it default.

since custom hosts are not supported, it is better to give option to add well known hosts.

actually,this blocks as the name indicates. if i want to completely block porn, the solution is that i would choose first one

**Comment by beerisgood** [comment]
you don't understand what censoring is?

It's also not the goal of NextDNS

**Comment by gitpubber** [comment]
nextdns allows to block any domain. why not this?

**Comment by gitpubber** [comment]
@richieheijmans @romaincointepas  @rs please do consider. so,we already have blocklist to block whatsapp,google,etc.

this one will be additional blocklist.that's it. this adds 3 more variants of Steven Black Hosts

**Comment by beerisgood** [comment]
upvoting your own posts doesn't make sense and is ridiculous

**Comment by quantumpacket** [comment]
The reason this should not be added is that it adds the variant "fakenews", which is what @beerisgood is meaning when it comes to censorship. Such lists are politically opinionated and should not be something that NextDNS offers (especially bundled with other lists) so at to remain a neutral provider.

**Pull request closed without merging**
