### PR TITLE
Added x0uid Spotify Ad Block List

### LINKED ISSUE #343: Spotify Ads Hosts List
Would be good to block Spotify Ad's and tracking using this hosts list: https://github.com/x0uid/SpotifyAdBlock

### PR DESCRIPTION
**Pull request by s0kil**
Fixes #343

### CODE REVIEW

**Comment by crssi** [comment]
This is nice... can you drop the https://github.com/nextdns/metadata/blob/master/privacy/blocklists/chef-koch-spotify.json in favor of this one.

See: https://github.com/nextdns/metadata/issues/340#issuecomment-663628459

**Comment by romaincointepas** [comment]
I don't get why this blocklist has a separate whitelist (vs. a combined final hosts file).

https://github.com/x0uid/SpotifyAdBlock/issues/24 is not reassuring.

**Comment by s0kil** [comment]
@crssi Seems like that should be done in a separate PR.

**Comment by crssi** [comment]
Actually I do not use Spotify at all, but I do think any project should not support plagiarisms and in this case CHEF-KOCH.
It would be a shame that supporting plagiarism would drop a shadow onto reliability. 😞

**Comment by romaincointepas** [comment]
@x0uid would you be open to providing a unified blocklist that automatically removes the domains from the whitelist from the main list?

I may be missing something but I don't get the duo *blocklist with false positives* then *separate whitelist*.

**Pull request closed without merging**
