### PR TITLE
[Parentalcontrol] Add additional domains for services

### PR DESCRIPTION
**Pull request by emilstahl**

### CODE REVIEW

**Comment by romaincointepas** [comment]
Awesome.

Before merging, could you give an example for each affiliate/tracking domain added where it blocks an unavoidable link (or similar)?

**Comment by emilstahl** [comment]
@romaincointepas 
**partner-ads.com:** 
The "bliv partner nu" button on this site https://moneybrewer.dk/partner-ads-link/

**online.digital-advisor.com:**
All the buttons on this site https://webhotelsoversigt.dk/rabatkode/2-rabatkode-til-simply

**Comment by scafroglia93** [comment]
From research I see that Mullvad is very popular among Nextdns users, blocking it would not be a smart thing

**Comment by emilstahl** [comment]
@scafroglia93 I don't understand how this is relevant or an issue. Block Bypass Methods is not enabled by default, and is supposed to block VPNs?
Screen Shot 2020-04-23 at 21 16 42

**Comment by romaincointepas** [comment]
Thanks! And done, with a few exceptions:

- `doh.applied-privacy.net` was correct.
- we don't feel like whitelisting partner-ads.com for now, the other was added.
- some snapshat domains you added are not in used anymore (google 404), removed them.

Side note: can you split in multiple issues next time?

**Comment by emilstahl** [comment]
@romaincointepas 
1. doh.applied-privacy.net was **not** removed in my commit, only a duplicate entry was removed? As you removed it from your commit, the domain is sill listed two times, line 38 and 60? I have created a new pull request..
2. Partner-ads is a big affiliate network in Denmark, and it breaks all affiliate links from them. Should I find better example?
3. Check.
4. Sure.

**Comment by romaincointepas** [comment]
@emilstahl 

1. Oh, my bad, merged 👍 

2. Yep. The way we approach this is that a domain has to be *blocking* way more than it is used for tracking. And the example you gave me somehow redirects to a partner-ads.com website itself linking to partner-ads.com.

3. Not sure what you mean by "Check", did I remove an active domain by mistake?

**Comment by emilstahl** [comment]
@romaincointepas 
1. 👍 
2. I have created #174 with a proper example.
3. Just meant to ay "got it" or "acknowledged" :)

**Pull request closed without merging**
