### PR TITLE
Delete nsa-blocklist.json

### PR DESCRIPTION
**Pull request by beerisgood**
Chef-Koch got banned on GitHub & GitLab because of e.g. steal work from others without any info.
Read about him at arkenfox/user.js#323

This PR also solve https://github.com/nextdns/metadata/issues/340 & https://github.com/nextdns/metadata/issues/408 & https://github.com/nextdns/metadata/issues/387

You should really take action now instead of waiting longer. Doesn't make any sense

### CODE REVIEW

**Comment by michaelb-ae** [comment]
i'm not for it (maybe rename the list (remove chef-koch)), but removing all the list is like removing protection some user want to have.

**Comment by beerisgood** [comment]
> i'm not for it (maybe rename the list (remove chef-koch)), but removing all the list is like removing protection some user want to have.

Their isn't any protection with this list. It's nonsense and also totally outdated.

**Comment by crssi** [comment]
Totally agree with @beerisgood.

If anyone is using it and feel that is has some impact... NextDNS now have a really great feature for diagnostics.... you can download logs for further analysis.
The simplest method: dowload logs, import into EXCEL as CSV, select the `reason` column filter and choose to filter out the records block for NSA reason... and you will surelly get 0 (zero) records.

**Comment by michaelb-ae** [comment]
Yes but it's not up to you to decide what rules the user want (i don't use them but some want it), and since i'm allways defend liberty to do what the user whant.
Since we cannot add external rules i'm for letting it.
It's not because YOU don't use it or want it that it should be removed, if i follow your thoughts, i will ask to remove 80% of these list because i d'ont see their utility since i use a list who contain them all, and duplicate must be removed.

**Comment by beerisgood** [comment]
> Yes but it's not up to you to decide what rules the user want

So same for you. I also don't say that.

And my PR isn't about removing lists against my opinion.
I only recommend removing this outdated list which doesn't block anything and will only end with false positives.

**Comment by scafroglia93** [comment]
remove this crap list please

**Comment by hueto902** [comment]
If you don't use ok, it's your choice, but if someone is using, it's their choice after all, and probably there is people using it, even if it's just a few.
**Removing the list will affect the others using it but not removing the list won't affect you**, _so cut the BS._
I know you probably hate CK but that has little to nothing to do with the blocklist or the people using it.
This issue has been addressed before and closed, months passed and the list is still there as an option if someone wants, freedom of choice, sincerely please refrain from creating the same issue again and again.

**Comment by beerisgood** [comment]
NextDNS don’t care for a lot of things. 
i guess this (and other) issues and/ or pull requests will never be solved.

**Comment by pYFZOS5** [comment]
>Chef-Koch got banned on GitHub & GitLab because of e.g. steal work from others without any info.

@beerisgood You have explained the reason, in this case you must consider to find and provide each original works for nextdns and as i saw on forums, some users say that it's not possible to find original source of few. actually that was a good repository somehow but the problem maintainer shared them as an own work.

@scafroglia93 that's not a crap; i have a downloaded copy of that repository (before got banned) then checked random domains and those are still valid but i dont have time to check entire thing.

I don't know how "steal work from others" become a totally useless thing.

@BirdInFire @hueto902 It's nice to see you :)

**Comment by beerisgood** [comment]
> @scafroglia93 that's not a crap; i have a downloaded copy of that repository (before got banned) then checked random domains and those are still valid but i dont have time to check entire thing.
> 

It is, because it makes absolutely no sense to block such domains. As if that would help anything against such a government, especially since there are also IP addresses and other ways.
The very idea of wanting to block such things is ridiculous and only shows ignorance.

> I don't know how "steal work from others" become a totally useless thing.
> 

Because you simply don't do that. If you copy work without permission, at least add the original author as a reference. Furthermore, these copied works were not maintained by chef-koch, because he simply lacked the knowledge.

**Pull request closed without merging**
