### PR TITLE
added updates.bravesoftware.com

### PR DESCRIPTION
**Pull request by aelisya**
added updates.bravesoftware.com used by the installer of brave to download and install it, when installed it can immediately bypass the security with tor

### CODE REVIEW

**Comment by romaincointepas** [comment]
NextDNS wildcard-blocks, should we just add `bravesoftware.com` instead?

**Comment by aelisya** [comment]
it's better yes but i only have reported the one the installer use ^^

**Comment by aelisya** [comment]
it's done @romaincointepas

**Comment by aelisya** [comment]
i'm closing, since the commit 3db33f0ac72d0b2efd950370e3e3f8b22d7d671f do this pull request not needed anymore

**Pull request closed without merging**
