### PR TITLE
[Cryptojacking] https://zerodot1.gitlab.io/CoinBlockerLists/hosts

### PR DESCRIPTION
**Pull request by ZeroDot1**
This should solve PR #70.

### CODE REVIEW

**Comment by romaincointepas** [comment]
Your list (if I remember correctly) used to block api.coinbase.com, that's why we didn't include it. Is it safe now and only containing cryptojacking domains (with no false positives with cryptocurrency-related domains)?

**Comment by ZeroDot1** [comment]
`api.coinbase.com` is not included in the CoinBlockerLists, that was a false positive.
Since the problem is solved you can use the list without any problems, if there are false positives please let me know and I will solve the problem as soon as possible.

**Comment by romaincointepas** [comment]
@ZeroDot1 what's the difference between `hosts` and `hosts_browser`?

**Comment by ZeroDot1** [comment]
Hosts blocks all miners that can be found, and Hosts_Browser only blocks browser mining.

**Comment by scafroglia93** [comment]
+1 for me

**Comment by romaincointepas** [comment]
@ZeroDot1 Got it. In that case is there a specific reason why this PR links to `hosts_browser` instead of `hosts`? Is it a safer (as in, less false positives) build?

**Comment by ZeroDot1** [comment]
Hi @romaincointepas , sorry for the late answer.
Cryptojacking is used mostly in browsers or browser-like applications, so the list `hosts_browser` contains only IOCs related to cryptojacking.
The Hosts list blocks mining completely independent of the system or software.
To prevent cryptojacking I recommend to use only the hosts brwoser.

**Comment by romaincointepas** [comment]
Added, thanks!

**Pull request closed without merging**
