### PR TITLE
Create oisd-extra.json

### PR DESCRIPTION
**Pull request by iGlitch**
Add the new Extra list from oisd containing "controversial domains" (doubleclick.net, google-analytics.com, googleadservices.com, googletagmanager.com, googletagservices.com, amazon-adsystem.com etc)

### CODE REVIEW

**Comment by beerisgood** [comment]
Just no.
See https://github.com/nextdns/metadata/issues/699#issuecomment-860999224

**Comment by romaincointepas** [comment]
@beerisgood one more "Just no" like this and it's a temporary ban.

**Comment by iGlitch** [comment]
Just like how enabling/disabling every list is an option, you would still have the option to keep this off. Just because it may be included doesn't mean it will be forcibly applied to every user. Keep it off if you don't like it, there might be a few people that actually do like the list :)
Though maybe the description could have more of a warning than just the default perhaps.

**Comment by romaincointepas** [comment]
Duplicate of https://github.com/nextdns/blocklists/issues/36.

**Pull request closed without merging**
