### PR TITLE
Add some url-shorteners domains

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Some other url-shorteners domains

### CODE REVIEW

**Comment by romaincointepas** [comment]
We are splitting up this monorepo and have moved this to https://github.com/nextdns/url-shorteners-domains.

But thinking about it, we should just use your repo and deprecate ours, you seem to be maintaining it pretty well. What do you think?

**Comment by PeterDaveHello** [comment]
Sure thing, any usages that follow the license are welcome.

**Comment by PeterDaveHello** [comment]
@romaincointepas btw, is it possible that you can have an option to manually enable or disable use url shortener domains as allowlist?

AFAIK, some users would like to use it as blocklist, like both RethinkDNS and Control D are using it as blocklist, not sure if it's good enough to always let those domains bypass the blocking.

**Comment by romaincointepas** [comment]
@PeterDaveHello we don't really see a valid enough use case for a feature that would block URL shorteners.

**Comment by romaincointepas** [comment]
@PeterDaveHello Before I delete https://github.com/nextdns/url-shorteners-domains, do you think you could save/merge whatever domains missing from https://github.com/PeterDaveHello/url-shorteners (`xep.li`, `glnk.io`, ...)?

**Comment by PeterDaveHello** [comment]
@romaincointepas I mean that maybe not everyone would like to let the list unlock all other blockers? For those you'd like to add to my list, would you send a pull request that contains those certain url shorteners? I'd arrange some time to verify the data.

**Pull request closed without merging**
