### PR TITLE
add "instafeed.nfcube.com"

### PR DESCRIPTION
**Pull request by beerisgood**
see https://instafeed.nfcube.com/

### CODE REVIEW

**Comment by romaincointepas** [comment]
I don't get this one, how is that related to stopping Instagram from being accessed/used?

**Comment by beerisgood** [comment]
This service integrate Instagram as "feed" so it can circumstances blocking instagram domain.

This doesn't stop instagram itself but add protection against circumstances.

**Comment by romaincointepas** [comment]
This is a pretty good point regarding what could be called service proxies, I'm keen to add them. A quick google search showed https://www.picuki.com/ for instagram as well, etc. There are probably quite a few for some services.

**Comment by romaincointepas** [comment]
https://instafeed.nfcube.com seems to be some developer thingy though, not something someone can easily use to *still browse Instagram*.

We are okay to add pure service proxies like https://www.picuki.com for Instagram.

Closing this one, but feel free to open issues or PR for service proxies.

**Pull request closed without merging**
