### PR TITLE
Updated Web Proxies

### PR DESCRIPTION
**Pull request by mark4409**
Added a bunch of new web proxies obtained by scraping various online web proxy listings

### CODE REVIEW

**Comment by quantumpacket** [comment]
@mark4409 I was going to send a PR for these, but if you could add them to this PR?

anony.men
proxurf.com
tomwebproxy.com
us.youproxy.xyz
unblockproxy.win
videoproxy.icu

**Comment by romaincointepas** [comment]
We would like to avoid adding "temporary proxy domains" in this list, and stick to popular proxy services endpoints (otherwise it will become hell to maintain and may lead to false positives).

Would you be willing to update your PR accordingly?

**Comment by quantumpacket** [comment]
> Prevent or hinder the use of methods that can help bypass NextDNS filtering on the network. This includes VPNs, proxies, Tor-related software and encrypted DNS providers.

The feature description should be updated to reflect such a policy, so as not to give a false sense of coverage.

**Comment by quantumpacket** [comment]
@rs I noticed a couple of merges were done for the bypass methods recently. Could this be merged or closed? Also, what is the official policy on adding domains to this list? I'm seeing conflicting requirements from the above comment about this PR and the recent merges.

**Comment by mark4409** [comment]
I scraped these sites in February. It's November now and so the list is already quite dated. I'm probably better off doing a new scrape

**Pull request closed without merging**
